<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>design – Axolotl</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../../">
<link href="../../../../favicon.jpg" rel="icon" type="image/jpeg">
<script src="../../../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../../site_libs/quarto-html/quarto-syntax-highlighting-dark-d0ae9245876894da5ac7e18953ecc5cc.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../../site_libs/bootstrap/bootstrap-ab6ebd6eb475c4578b58908bc314f719.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-9KYCVJBNMQ"></script>

<script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-9KYCVJBNMQ', { 'anonymize_ip': true});
</script>


<link rel="stylesheet" href="../../../../styles.css">
</head>

<body class="nav-sidebar docked nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../../../../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../../../../image/axolotl_logo_digital_white.svg" alt="" class="navbar-logo light-content">
    <img src="../../../../image/axolotl_logo_digital_white.svg" alt="" class="navbar-logo dark-content">
    </a>
  </div>
        <div class="quarto-navbar-tools tools-wide tools-end">
    <a href="https://twitter.com/axolotl_ai" title="" class="quarto-navigation-tool px-1" aria-label=""><i class="bi bi-twitter"></i></a>
    <a href="https://github.com/axolotl-ai-cloud/axolotl/" title="" class="quarto-navigation-tool px-1" aria-label=""><i class="bi bi-github"></i></a>
    <a href="https://discord.gg/7m9sfhzaf3" title="" class="quarto-navigation-tool px-1" aria-label=""><i class="bi bi-discord"></i></a>
</div>
          <div id="quarto-search" class="" title="Search"></div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Home</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Getting Started</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../../docs/getting-started.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Quickstart</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../../docs/choosing_method.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Which Fine-Tuning Method Should I Use?</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../../docs/installation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Installation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../../docs/inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Inference and Merging</span></a>
  </div>
</li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false">
 <span class="menu-text">Model Guides</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../../docs/models/kimi-linear.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Kimi Linear</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../../docs/models/plano.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Plano Orchestrator</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../../docs/models/mimo.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">MiMo</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../../docs/models/internvl3_5.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">InternVL 3.5</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../../docs/models/olmo3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">OLMo 3</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../../docs/models/trinity.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Trinity</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../../docs/models/arcee.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Arcee AFM</span></a>
  </div>
</li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false">
 <span class="menu-text">Ministral3</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth3 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../../docs/models/ministral3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Ministral3</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../../docs/models/ministral3/think.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Ministral 3 Thinking</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../../docs/models/ministral3/vision.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Ministral 3 Vision</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false">
 <span class="menu-text">Magistral</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth3 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../../docs/models/magistral.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Magistral</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../../docs/models/magistral/think.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Magistral Thinking</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../../docs/models/magistral/vision.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Magistral Vision</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../../docs/models/ministral.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Ministral</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../../docs/models/mistral-small.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Mistral Small 3.1/3.2</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../../docs/models/voxtral.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Voxtral</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../../docs/models/devstral.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Devstral</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../../docs/models/mistral.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Mistral 7B</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../../docs/models/llama-4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Llama 4</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../../docs/models/llama-2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Llama 2</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../../docs/models/qwen3-next.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Qwen 3 Next</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../../docs/models/qwen3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Qwen 3</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../../docs/models/gemma3n.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Gemma 3n</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../../docs/models/apertus.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Apertus</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../../docs/models/gpt-oss.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">GPT-OSS</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../../docs/models/seed-oss.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Seed-OSS</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../../docs/models/phi.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Phi</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../../docs/models/smolvlm2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">SmolVLM 2</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../../docs/models/granite4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Granite 4</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../../docs/models/LiquidAI.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Liquid Foundation Models 2</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../../docs/models/hunyuan.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Hunyuan</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../../docs/models/jamba.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Jamba</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../../docs/models/orpheus.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Orpheus</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../../docs/cli.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Command Line Interface (CLI)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../../docs/telemetry.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Telemetry</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../../docs/config-reference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Config Reference</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../../docs/api" class="sidebar-item-text sidebar-link">
 <span class="menu-text">API Reference</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../../../docs/dataset-formats/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Dataset Formats</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../../docs/dataset-formats/pretraining.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Pre-training</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../../docs/dataset-formats/inst_tune.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Instruction Tuning</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../../docs/dataset-formats/conversation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Conversation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../../docs/dataset-formats/stepwise_supervised.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Stepwise Supervised Format</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../../docs/dataset-formats/template_free.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Template-Free</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../../docs/dataset-formats/tokenized.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Custom Pre-Tokenized Dataset</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">Deployments</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../../docs/docker.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Docker</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../../docs/multi-gpu.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Multi-GPU</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../../docs/multi-node.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Multi Node</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../../docs/ray-integration.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Ray Train</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../../docs/amd_hpc.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AMD GPUs on HPC Systems</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../../docs/mac.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Mac M-series</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true">
 <span class="menu-text">How To Guides</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../../docs/multimodal.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">MultiModal / Vision Language Models (BETA)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../../docs/rlhf.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">RLHF (Beta)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../../docs/grpo.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">GRPO Training</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../../docs/ebft.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">EBFT Training</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../../docs/vllm_serving.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">vLLM Serving for GRPO Training</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../../docs/reward_modelling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Reward Modelling</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../../docs/lr_groups.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Learning Rate Groups</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../../docs/lora_optims.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">LoRA Optimizations</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../../docs/dataset_loading.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Dataset Loading</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../../docs/qat.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Quantization Aware Training (QAT)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../../docs/quantize.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Quantization with torchao</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../../docs/optimizations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Optimizations Guide</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="true">
 <span class="menu-text">Core Concepts</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../../docs/batch_vs_grad.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Batch size vs Gradient accumulation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../../docs/dataset_preprocessing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Dataset Preprocessing</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../../docs/streaming.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Streaming Datasets</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../../docs/multipack.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Multipack (Sample Packing)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../../docs/mixed_precision.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Mixed Precision Training</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../../docs/optimizers.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Optimizers</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../../docs/attention.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Attention</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="true">
 <span class="menu-text">Advanced Features</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../../docs/fsdp_qlora.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">FSDP + QLoRA</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../../docs/torchao.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">PyTorch ao</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../../docs/custom_integrations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Custom Integrations</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../../docs/sequence_parallelism.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Sequence Parallelism</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../../docs/gradient_checkpointing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Gradient Checkpointing, Activation Offloading, and Layer Offloading</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../../docs/nd_parallelism.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">N-D Parallelism (Beta)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../../docs/expert_quantization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">MoE Expert Quantization</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="true">
 <span class="menu-text">Troubleshooting</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-10" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../../docs/faq.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">FAQ</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../../docs/training_stability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Training Stability &amp; Debugging</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../../docs/debugging.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Debugging</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../../docs/nccl.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">NCCL</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#purpose" id="toc-purpose" class="nav-link active" data-scroll-target="#purpose">Purpose</a></li>
  <li><a href="#workstream-shape-ratifications-drift-from-plan.md" id="toc-workstream-shape-ratifications-drift-from-plan.md" class="nav-link" data-scroll-target="#workstream-shape-ratifications-drift-from-plan.md">Workstream-shape ratifications (drift from <code>plan.md</code>)</a></li>
  <li><a href="#directory-layout" id="toc-directory-layout" class="nav-link" data-scroll-target="#directory-layout">Directory Layout</a></li>
  <li><a href="#module-specs" id="toc-module-specs" class="nav-link" data-scroll-target="#module-specs">Module Specs</a>
  <ul class="collapse">
  <li><a href="#plugin.py-m5" id="toc-plugin.py-m5" class="nav-link" data-scroll-target="#plugin.py-m5">plugin.py (M5)</a></li>
  <li><a href="#args.py-m5" id="toc-args.py-m5" class="nav-link" data-scroll-target="#args.py-m5">args.py (M5)</a></li>
  <li><a href="#profiler-m1" id="toc-profiler-m1" class="nav-link" data-scroll-target="#profiler-m1">profiler/ (M1)</a></li>
  <li><a href="#chunk-m2" id="toc-chunk-m2" class="nav-link" data-scroll-target="#chunk-m2">chunk/ (M2)</a></li>
  <li><a href="#block-m3" id="toc-block-m3" class="nav-link" data-scroll-target="#block-m3">block/ (M3)</a></li>
  <li><a href="#cost-m4" id="toc-cost-m4" class="nav-link" data-scroll-target="#cost-m4">cost/ (M4)</a></li>
  <li><a href="#search-m4" id="toc-search-m4" class="nav-link" data-scroll-target="#search-m4">search/ (M4)</a></li>
  <li><a href="#runtime-m2m3-integration" id="toc-runtime-m2m3-integration" class="nav-link" data-scroll-target="#runtime-m2m3-integration">runtime/ (M2+M3 integration)</a></li>
  <li><a href="#api-m4" id="toc-api-m4" class="nav-link" data-scroll-target="#api-m4">api/ (M4)</a></li>
  </ul></li>
  <li><a href="#key-data-structures" id="toc-key-data-structures" class="nav-link" data-scroll-target="#key-data-structures">Key Data Structures</a></li>
  <li><a href="#plugin-integration-m5" id="toc-plugin-integration-m5" class="nav-link" data-scroll-target="#plugin-integration-m5">Plugin Integration (M5)</a></li>
  <li><a href="#cross-module-dependency-graph" id="toc-cross-module-dependency-graph" class="nav-link" data-scroll-target="#cross-module-dependency-graph">Cross-Module Dependency Graph</a>
  <ul class="collapse">
  <li><a href="#multi-gpu" id="toc-multi-gpu" class="nav-link" data-scroll-target="#multi-gpu">Multi-GPU</a></li>
  </ul></li>
  <li><a href="#out-of-scope" id="toc-out-of-scope" class="nav-link" data-scroll-target="#out-of-scope">Out of Scope</a></li>
  <li><a href="#design-decisions-previously-open-questions-now-resolved" id="toc-design-decisions-previously-open-questions-now-resolved" class="nav-link" data-scroll-target="#design-decisions-previously-open-questions-now-resolved">Design Decisions (previously open questions, now resolved)</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block"></header>




<section id="purpose" class="level2">
<h2 class="anchored" data-anchor-id="purpose">Purpose</h2>
<p>This package is a from-scratch Python implementation of the ProTrain memory manager (MLSys 2026, arXiv 2406.08334), shipped as an <strong>Axolotl plugin</strong> (<code>BasePlugin</code> subclass). It owns per-rank memory policy on top of ZeRO-3: hierarchical chunk management for model states (params / grads / optim states), interleaved block management for activations, a memory-aware profiler, a 4-knob cost model, and an automatic searcher. It does NOT own data parallelism collectives (delegates to <code>torch.distributed</code>), training-loop control flow, trainer orchestration, TP/PP, FP8, or any changes to Axolotl core files. Activation is opt-in via <code>plugins: [axolotl.integrations.protrain]</code> in the user YAML; mutual exclusion with <code>deepspeed:</code> and <code>fsdp:</code> is enforced by a pydantic validator in <code>args.py</code>.</p>
</section>
<section id="workstream-shape-ratifications-drift-from-plan.md" class="level2">
<h2 class="anchored" data-anchor-id="workstream-shape-ratifications-drift-from-plan.md">Workstream-shape ratifications (drift from <code>plan.md</code>)</h2>
<p>Two intentional deviations from the original plan, both ratified after M5 review:</p>
<ol type="1">
<li><p><strong>Package path: <code>src/axolotl/integrations/protrain/</code> (not <code>src/axolotl/memory/protrain/</code>)</strong>. Plan specified the latter; we landed on the former. The driver is Axolotl’s own convention — <code>src/axolotl/integrations/</code> is the canonical home for <code>BasePlugin</code> subclasses (<code>spectrum</code>, <code>kd</code>, <code>cut_cross_entropy</code>, etc.), and ProTrain ships as a plugin. Putting it under <code>memory/</code> would have required teaching <code>prepare_plugins</code> a non-standard discovery path, plus diverging from the test conventions every other integration follows (<code>tests/integrations/&lt;name&gt;/</code>). The functional contract of “no edits to Axolotl core” is preserved unchanged.</p></li>
<li><p><strong>DESIGN.md length: ~260 lines (plan said “under 200”)</strong>. The plan’s 200-line bound was an M0 hygiene target before M7 ZeRO-3 sharding and the Mode A/B/C auto-selector existed — those sections account for most of the over-budget content (~50 lines of multi-GPU spec + benchmark results that didn’t exist when the plan was written). Trimming would lose multi-GPU integration documentation that operators actively reference. Length cap formally raised to 350 lines; sections must continue to map 1:1 onto subpackages (no narrative essays).</p></li>
</ol>
</section>
<section id="directory-layout" class="level2">
<h2 class="anchored" data-anchor-id="directory-layout">Directory Layout</h2>
<pre><code>src/axolotl/integrations/protrain/
├── __init__.py                  # re-exports ProTrainArgs + ProTrainPlugin
├── DESIGN.md                    # this file
├── plugin.py                    # BasePlugin subclass: get_input_args / post_model_load / create_optimizer
├── args.py                      # ProTrainArgs pydantic model + DS/FSDP mutex validator
├── types.py                     # shared dataclasses (ProfilerTrace, ChunkLayout, ...)
├── profiler/
│   ├── __init__.py
│   ├── trace.py                 # single-iter forward/backward hook driver
│   ├── memory_deltas.py         # intra-op + inter-op Δ capture via cuda.memory_stats
│   ├── on_demand.py             # allocate-before-use / free-after tensor mode
│   ├── hw_bench.py              # H2D/D2H + NCCL gather/reduce microbenchmarks
│   └── cache.py                 # on-disk cache keyed by (arch_hash, bs, seq, sku, world)
├── chunk/
│   ├── __init__.py
│   ├── layout.py                # param→chunk assignment, exec-order intra-chunk reorder
│   ├── sizing.py                # S_chunk grid search over {32,64,128,256} MB
│   ├── manager.py               # persistent/non-persistent split, gather/offload drivers
│   ├── buffer_pool.py           # pre-allocated chunk buffer pool, forward→backward reuse
│   ├── pinned_alloc.py          # ctypes → cudaHostAlloc, precise-size (App B.2)
│   └── optim.py                 # DeepSpeedCPUAdam adapter (non-persist) + GPU FusedAdam (persist)
├── block/
│   ├── __init__.py
│   ├── strategy.py              # BlockMode enum {NONE, CKPT, SWAP}
│   ├── dispatcher.py            # per-block forward wrapper honoring selected mode
│   ├── checkpoint.py            # CKPT path (torch.utils.checkpoint adapter)
│   ├── swap.py                  # SWAP wrapper: D2H in fwd / H2D in bwd on _swap_stream
│   ├── swap_pool.py             # pinned-RAM activation slot pool
│   └── layout_rules.py          # placement rules: swap-early / unopt-late / interleave
├── cost/
│   ├── __init__.py
│   ├── runtime.py               # Eqs. 2–7, per-chunk max(compute, comm) roofline
│   ├── memory.py                # Eqs. 8–11, op-walk peak + α=1.10 fragmentation
│   └── bandwidth.py             # contention model when n_swap&gt;0 competes with prefetch
├── search/
│   ├── __init__.py
│   ├── knobs.py                 # CostConfig + bound derivation (N_chunk, N_block, N_interval)
│   └── exhaustive.py            # 4-knob enumeration with memory-ascending pruning
├── runtime/
│   ├── __init__.py
│   ├── streams.py               # single-stream alloc scheme (App B.2)
│   ├── scheduler.py             # prefetch / reduce-offload / CPU-step / swap orchestration
│   └── hooks.py                 # install/uninstall fwd/bwd hooks on the user model
└── api/
    ├── __init__.py
    ├── model_wrapper.py         # protrain_model_wrapper() — called from plugin.post_model_load
    └── optim_wrapper.py         # protrain_optimizer_wrapper() — called from plugin.create_optimizer</code></pre>
</section>
<section id="module-specs" class="level2">
<h2 class="anchored" data-anchor-id="module-specs">Module Specs</h2>
<p>Every entry: Inputs · Outputs · Paper ref · Milestone.</p>
<section id="plugin.py-m5" class="level3">
<h3 class="anchored" data-anchor-id="plugin.py-m5">plugin.py (M5)</h3>
<ul>
<li><code>class ProTrainPlugin(BasePlugin)</code> — thin shim.
<ul>
<li><code>get_input_args() -&gt; "axolotl.integrations.protrain.args.ProTrainArgs"</code>.</li>
<li><code>post_model_load(cfg, model)</code> — constructs <code>HardwareProfile</code>, runs profiler (cached), calls <code>protrain_model_wrapper(model, ...)</code>, stashes <code>WrappedModel</code> on <code>cfg</code> for <code>create_optimizer</code> to pick up.</li>
<li><code>create_optimizer(cfg, trainer) -&gt; Optimizer</code> — returns <code>protrain_optimizer_wrapper(wrapped_model)</code>; returns <code>None</code> when plugin is inactive.</li>
<li><code>post_trainer_create(cfg, trainer)</code> — installs any trainer-level callbacks if needed for metric reporting.</li>
</ul></li>
</ul>
</section>
<section id="args.py-m5" class="level3">
<h3 class="anchored" data-anchor-id="args.py-m5">args.py (M5)</h3>
<ul>
<li><code>class ProTrainArgs(BaseModel)</code> — fields: <code>protrain_auto_memory: bool = True</code>, optional manual knob overrides <code>protrain_n_persist / n_buffer / n_swap / n_checkpoint</code> for debugging, <code>protrain_cache_dir: Path | None</code>.</li>
<li><code>model_validator</code> — rejects <code>plugins: [...protrain...]</code> + (<code>deepspeed</code> set) or (<code>fsdp</code> / <code>fsdp_config</code> set). Pattern cloned from <code>integrations/spectrum/args.py:32-47</code>.</li>
</ul>
</section>
<section id="profiler-m1" class="level3">
<h3 class="anchored" data-anchor-id="profiler-m1">profiler/ (M1)</h3>
<ul>
<li><code>trace.py</code> — <code>run_trace(model: nn.Module, batch: dict, cfg: ProfilerConfig) -&gt; ProfilerTrace</code>. Installs pre/post fwd + bwd hooks, records op order, delegates Δ capture. §3.2.</li>
<li><code>memory_deltas.py</code> — <code>intra_op_delta(op) -&gt; int</code>, <code>inter_op_delta(prev, curr) -&gt; int</code> from <code>torch.cuda.memory_stats()</code>. Catches the ~17% invisible peak. §3.2, App A.2.</li>
<li><code>on_demand.py</code> — <code>class OnDemandTensorMgr</code> context; <code>allocate_inputs(op)</code> / <code>free_after(op)</code>. Enables profiling models larger than single-GPU. §3.2. The on-demand pre-gather hook is registered with <code>prepend=True</code> so it fires BEFORE the trace driver’s <code>_pre_forward</code>; the trace’s <code>allocated_before</code> snapshot therefore already includes the gathered param, and <code>intra_op_delta = peak − allocated_before</code> captures only workspace + output (not the gather). Post-release stays FIFO so it fires after the trace’s <code>_post_forward</code> peak read. Same ordering for backward (<code>prepend=True</code> on <code>register_full_backward_pre_hook</code>, FIFO on the post hook).</li>
<li><code>hw_bench.py</code> — <code>measure_pcie() -&gt; BW</code>, <code>measure_nccl(world_size) -&gt; NcclTable</code>. §3.2.</li>
<li><code>cache.py</code> — <code>load(key) -&gt; ProfilerTrace | None</code>, <code>save(key, trace)</code>. Key = <code>(arch_hash, bs, seq, sku, world)</code>. §7. The <code>TRACE_VERSION</code> constant prefixes the cache key, so a bump invalidates all prior entries silently. Versions: v2 added per-op latencies, v3 added measured Adam throughput, v4 added hook-dispatch calibration (hooked/steady fwd-wall), v5 added the aggregate steady-fwd peak, v6 added per-block steady peaks (tighter cap for fractional-NONE configs), v7 changed the steady-state methodology from a single iteration to a 4-iter hot loop (2 warmup + 2 measured, median) and added a best-effort steady_bwd_wall. The fields list didn’t change at v7 but the recorded <em>values</em> shifted, so the cost model’s measured bwd/fwd-ratio path requires a fresh trace under the new methodology.</li>
</ul>
</section>
<section id="chunk-m2" class="level3">
<h3 class="anchored" data-anchor-id="chunk-m2">chunk/ (M2)</h3>
<ul>
<li><code>layout.py</code> — <code>build_layout(model, exec_order: list[ParamId], S_chunk: int) -&gt; ChunkLayout</code>. Groups params per transformer block, reorders intra-chunk by first use, shared params at first occurrence. §3.1.1.</li>
<li><code>sizing.py</code> — <code>pick_S_chunk(model_state_sizes: list[int], candidates=(32&lt;&lt;20, 64&lt;&lt;20, 128&lt;&lt;20, 256&lt;&lt;20)) -&gt; int</code>. Simulates fragmentation waste; returns argmin. App B.1.</li>
<li><code>manager.py</code> — <code>class ChunkManager</code>; <code>gather(chunk_id)</code>, <code>offload(chunk_id)</code>, <code>mark_persistent(first_n)</code>. §3.1.1.</li>
<li><code>buffer_pool.py</code> — <code>class BufferPool(n_buffer: int, S_chunk: int)</code>; <code>acquire() / release()</code>; carries forward-resident buffers into backward. §3.1.1, §5.</li>
<li><code>pinned_alloc.py</code> — <code>pinned_alloc(n_buffer, S_chunk) -&gt; HostMemory</code>. <code>ctypes</code> → <code>cudaHostAlloc</code> with exact byte count. App B.2.</li>
<li><code>optim.py</code> — wraps <code>deepspeed.ops.adam.DeepSpeedCPUAdam</code> for non-persistent chunks, <code>apex.optimizers.FusedAdam</code> (or torch <code>FusedAdam</code>) for persistent. <code>step_async(chunk_id)</code> for CPU path to overlap GPU bwd. §5.</li>
</ul>
</section>
<section id="block-m3" class="level3">
<h3 class="anchored" data-anchor-id="block-m3">block/ (M3)</h3>
<ul>
<li><code>strategy.py</code> — <code>class BlockMode(Enum){NONE, CKPT, SWAP}</code>; <code>BlockStrategyMap = dict[int, BlockMode]</code>. §3.1.2.</li>
<li><code>dispatcher.py</code> — <code>wrap_block(block: nn.Module, mode: BlockMode) -&gt; nn.Module</code>. §3.1.2.</li>
<li><code>checkpoint.py</code> — thin wrapper over <code>torch.utils.checkpoint.checkpoint</code> (use_reentrant=False). §3.1.2.</li>
<li><code>swap.py</code> — <code>SwappedBlock</code>: D2H of output activation to a pinned-host slot on <code>_swap_stream</code> in forward; H2D back on <code>_swap_stream</code> in backward, with cross-stream event handshake. Pool + stream injected post-construction via <code>attach_runtime</code>. §3.1.2.</li>
<li><code>swap_pool.py</code> — <code>ActivationSwapPool</code>: pinned-host slot pool sized to <code>n_swap × prefetch_depth × max_act_bytes</code>. Backed by one <code>PinnedHostMemory</code> allocation; slot acquire/release tracked Python-side. §3.1.2.</li>
<li><code>layout_rules.py</code> — <code>assign_modes(n_swap, n_checkpoint, N_block) -&gt; BlockStrategyMap</code>. Swap-early / unopt-late / interleave. §3.1.2.</li>
</ul>
</section>
<section id="cost-m4" class="level3">
<h3 class="anchored" data-anchor-id="cost-m4">cost/ (M4)</h3>
<ul>
<li><code>runtime.py</code> — <code>estimate_runtime(cfg, trace, layout) -&gt; float</code>. Implements <strong>Eqs. 2–7</strong>: <code>T_iter = T_fwd + max(T_bwd + T_gpu_optim, T_cpu_optim)</code>, per-chunk <code>max(compute, comm)</code> roofline. §3.3, App A.1.</li>
<li><code>memory.py</code> — <code>estimate_peak(cfg, trace, layout, block_map) -&gt; int</code>. Implements <strong>Eqs. 8–10</strong> (op-walk) and <strong>Eq. 11</strong> (α = 1.10 fragmentation). Bumps at first op of each CKPT block. §3.3, App A.2.</li>
<li><code>bandwidth.py</code> — <code>effective_bw(cfg, hw) -&gt; float</code>. Derates prefetch BW when <code>n_swap &gt; 0</code>. §3.3.</li>
</ul>
</section>
<section id="search-m4" class="level3">
<h3 class="anchored" data-anchor-id="search-m4">search/ (M4)</h3>
<ul>
<li><code>knobs.py</code> — <code>CostConfig</code> dataclass + <code>derive_bounds(trace, layout) -&gt; Bounds(N_chunk, N_block, N_interval)</code>. §3.3.</li>
<li><code>exhaustive.py</code> — <code>search(trace, layout, capacity_bytes) -&gt; SearchResult</code>. Enumerates 4-tuple in memory-ascending order, prunes OOM, returns argmin(T_iter). §3.3.</li>
</ul>
</section>
<section id="runtime-m2m3-integration" class="level3">
<h3 class="anchored" data-anchor-id="runtime-m2m3-integration">runtime/ (M2+M3 integration)</h3>
<ul>
<li><code>streams.py</code> — single-default-stream allocator, manual dealloc sync. App B.2.</li>
<li><code>scheduler.py</code> — orchestrates (a) param prefetch, (b) grad reduce+offload, (c) CPU optimizer step, (d) activation swap. Respects <code>cost/bandwidth.py</code> budgets. §5, §6.</li>
<li><code>hooks.py</code> — <code>install(model)</code> / <code>uninstall()</code>; wires chunk &amp; block managers into fwd/bwd. §1.</li>
</ul>
</section>
<section id="api-m4" class="level3">
<h3 class="anchored" data-anchor-id="api-m4">api/ (M4)</h3>
<ul>
<li><code>model_wrapper.py</code> — <code>protrain_model_wrapper(model, model_config, hardware_profile) -&gt; WrappedModel</code>. §1.</li>
<li><code>optim_wrapper.py</code> — <code>protrain_optimizer_wrapper(wrapped_model) -&gt; Optimizer</code>. §1.</li>
</ul>
</section>
</section>
<section id="key-data-structures" class="level2">
<h2 class="anchored" data-anchor-id="key-data-structures">Key Data Structures</h2>
<p>All live in <code>types.py</code>. Fields expand during M1–M4:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="at">@dataclass</span>(frozen<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="kw">class</span> ProfilerTrace:</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>    op_order: <span class="bu">list</span>[OpRecord]                  <span class="co"># per-op: id, module_path, shape_sig</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>    intra_op_delta: <span class="bu">dict</span>[OpId, <span class="bu">int</span>]           <span class="co"># bytes</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>    inter_op_delta: <span class="bu">dict</span>[OpId, <span class="bu">int</span>]           <span class="co"># bytes</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>    activation_sizes: <span class="bu">dict</span>[BlockId, <span class="bu">int</span>]</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>    model_state_bytes: <span class="bu">int</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>    pcie_h2d_bps: <span class="bu">float</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>    pcie_d2h_bps: <span class="bu">float</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>    nccl_gather_s: <span class="bu">dict</span>[<span class="bu">int</span>, <span class="bu">float</span>]</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>    nccl_reduce_s: <span class="bu">dict</span>[<span class="bu">int</span>, <span class="bu">float</span>]</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>    arch_hash: <span class="bu">str</span><span class="op">;</span> bs: <span class="bu">int</span><span class="op">;</span> seq: <span class="bu">int</span><span class="op">;</span> sku: <span class="bu">str</span><span class="op">;</span> world: <span class="bu">int</span></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a><span class="at">@dataclass</span>(frozen<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a><span class="kw">class</span> ChunkLayout:</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>    S_chunk: <span class="bu">int</span></span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>    N_chunk: <span class="bu">int</span></span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>    chunks: <span class="bu">list</span>[<span class="bu">list</span>[ParamId]]</span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a>    param_to_chunk: <span class="bu">dict</span>[ParamId, <span class="bu">int</span>]</span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a>    block_to_chunks: <span class="bu">dict</span>[BlockId, <span class="bu">list</span>[<span class="bu">int</span>]]</span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a>BlockStrategyMap <span class="op">=</span> <span class="bu">dict</span>[<span class="bu">int</span>, BlockMode]</span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a><span class="at">@dataclass</span>(frozen<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb2-25"><a href="#cb2-25" aria-hidden="true" tabindex="-1"></a><span class="kw">class</span> CostConfig:</span>
<span id="cb2-26"><a href="#cb2-26" aria-hidden="true" tabindex="-1"></a>    n_persist: <span class="bu">int</span></span>
<span id="cb2-27"><a href="#cb2-27" aria-hidden="true" tabindex="-1"></a>    n_buffer: <span class="bu">int</span></span>
<span id="cb2-28"><a href="#cb2-28" aria-hidden="true" tabindex="-1"></a>    n_swap: <span class="bu">int</span></span>
<span id="cb2-29"><a href="#cb2-29" aria-hidden="true" tabindex="-1"></a>    n_checkpoint: <span class="bu">int</span></span>
<span id="cb2-30"><a href="#cb2-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-31"><a href="#cb2-31" aria-hidden="true" tabindex="-1"></a><span class="at">@dataclass</span>(frozen<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb2-32"><a href="#cb2-32" aria-hidden="true" tabindex="-1"></a><span class="kw">class</span> SearchResult:</span>
<span id="cb2-33"><a href="#cb2-33" aria-hidden="true" tabindex="-1"></a>    cfg: CostConfig</span>
<span id="cb2-34"><a href="#cb2-34" aria-hidden="true" tabindex="-1"></a>    block_map: BlockStrategyMap</span>
<span id="cb2-35"><a href="#cb2-35" aria-hidden="true" tabindex="-1"></a>    predicted_peak_bytes: <span class="bu">int</span></span>
<span id="cb2-36"><a href="#cb2-36" aria-hidden="true" tabindex="-1"></a>    predicted_iter_s: <span class="bu">float</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="plugin-integration-m5" class="level2">
<h2 class="anchored" data-anchor-id="plugin-integration-m5">Plugin Integration (M5)</h2>
<p>Zero diffs to Axolotl core files. The entire Axolotl surface consumed:</p>
<ul>
<li><code>BasePlugin</code> subclass at <code>src/axolotl/integrations/protrain/plugin.py</code></li>
<li><code>get_input_args</code> returns <code>ProTrainArgs</code> → pydantic merge handled by <code>axolotl/utils/schemas/config.py:1275</code> (<code>plugins:</code> field)</li>
<li><code>post_model_load(cfg, model)</code> hook — wraps post-LoRA so frozen LoRA base params contribute to persistent-chunk memory only</li>
<li><code>create_optimizer(cfg, trainer)</code> hook — returns ProTrain optimizer; <code>None</code> if disabled</li>
<li>Example YAML: <code>examples/protrain/3090-7b-lora.yml</code> — opts in via <code>plugins: [axolotl.integrations.protrain]</code></li>
</ul>
</section>
<section id="cross-module-dependency-graph" class="level2">
<h2 class="anchored" data-anchor-id="cross-module-dependency-graph">Cross-Module Dependency Graph</h2>
<ul>
<li><code>types.py</code> — depended on by everyone; depends on nothing.</li>
<li><code>profiler/*</code> — independent (M1). Depends only on <code>types.py</code> and <code>torch</code>.</li>
<li><code>chunk/*</code> — independent of profiler and block (M2). Uses <code>runtime/streams.py</code> and <code>runtime/hooks.py</code>.</li>
<li><code>block/*</code> — independent of profiler and chunk (M3). Uses <code>runtime/hooks.py</code>.</li>
<li><code>cost/*</code> — reads <code>ProfilerTrace</code> + <code>ChunkLayout</code> + <code>BlockStrategyMap</code> as <strong>data</strong>; no code-level dep on chunk/block internals (M4).</li>
<li><code>search/*</code> — depends on <code>cost/*</code> and <code>types.py</code> only (M4).</li>
<li><code>api/*</code> — depends on everything; built last.</li>
<li><code>plugin.py</code> — consumes <code>api/*</code> only; M5. Supports M1→M4 parallel fan-out: profiler, chunk, block run concurrently; cost+search starts once <code>ProfilerTrace</code> schema is frozen at end of M1.</li>
</ul>
<section id="multi-gpu" class="level3">
<h3 class="anchored" data-anchor-id="multi-gpu">Multi-GPU</h3>
<p>ProTrain is a per-rank memory policy. Two composition modes are supported; choose per-deployment by the <code>protrain_zero3_shard</code> YAML flag or by auto-detection.</p>
<p><strong>Mode A — DDP composition (pre-M7, still supported).</strong> Each rank runs its own full <code>protrain_model_wrapper</code> and holds a full (replicated) copy of every non-persistent chunk on pinned CPU. The trainer wraps the protrain’d module in <code>torch.nn.parallel.DistributedDataParallel</code>. DDP handles the cross-rank all-reduce on the trainable gradient set; ProTrain’s internal per-param <code>all_reduce</code> is silenced via <code>skip_internal_grad_reduce=True</code> (auto-set when <code>post_trainer_create</code> detects a DDP wrap). This mode is what the M6 multi-GPU throughput test exercises with <code>force_all_persistent=True</code> at world_size=4 on 3090s. It is the right choice for LoRA on ~7B where the frozen base fits in fp16 on one card (no memory pressure), because DDP’s bucketed allreduce is faster than ProTrain’s per-param reduction.</p>
<p><strong>Mode B — true ZeRO-3 chunk sharding (M7, new).</strong> Non-persistent chunks are partitioned across ranks on CPU: each rank holds only <code>ceil(chunk_bytes / world_size)</code> pinned bytes per chunk. Forward/backward sees the full chunk via <code>all_gather_into_tensor</code> at <code>ChunkManager.gather</code>; grads are reduced + partitioned via <code>reduce_scatter_tensor(op=AVG)</code> at <code>ChunkManager.reduce_grads_and_offload</code>. The CPU FusedAdam step runs only on the rank-local shard slice — each region’s flat <code>shard_param</code> is the Adam target, updated in place; the next gather’s <code>all_gather</code> propagates the update back to every rank’s replicated GPU copy.</p>
<p>Sharding handles BOTH homogeneous-dtype and mixed-dtype chunks (M7 follow-up). Each chunk is modelled as an ordered list of <code>_DtypeRegion</code> entries — one per maximal-length contiguous same-dtype byte run — and each region is independently partitioned across ranks and participates in its own <code>all_gather_into_tensor</code> / <code>reduce_scatter_tensor</code> collective. Homogeneous chunks lay out exactly one region and issue one collective per gather/reduce; mixed-dtype chunks (e.g.&nbsp;a Llama block with fp32 RMSNorm scales between fp16 linear layers) issue one collective per region. Persistent chunks are fully replicated in both modes.</p>
<p><strong>Auto-enable logic (pre-auto-mode).</strong> When <code>protrain_auto_mode=False</code> (explicit-override mode), <code>protrain_model_wrapper</code> decides at construction time:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th><code>world_size</code></th>
<th><code>force_all_persistent</code></th>
<th>outer DDP</th>
<th><code>zero3_shard</code> result</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>*</td>
<td>*</td>
<td>off (degrades to replicated even if True requested)</td>
</tr>
<tr class="even">
<td>&gt;1</td>
<td>True</td>
<td>*</td>
<td>off (everything is persistent)</td>
</tr>
<tr class="odd">
<td>&gt;1</td>
<td>False</td>
<td>auto-detected YES</td>
<td>off, AND <code>skip_internal_grad_reduce=on</code></td>
</tr>
<tr class="even">
<td>&gt;1</td>
<td>False</td>
<td>NO</td>
<td>on (M7 ZeRO-3 path)</td>
</tr>
</tbody>
</table>
<p>The user can override via the <code>protrain_zero3_shard: true/false</code> field on <code>ProTrainArgs</code>. When DDP is composed on top AND sharding was auto-enabled, <code>post_trainer_create</code> logs a WARNING (the two paths don’t compose cleanly); the operator should set <code>protrain_zero3_shard: false</code> in YAML for DDP deployments.</p>
<p><strong>Mode selection (auto, default).</strong> <code>protrain_auto_mode: true</code> (default) runs the searcher first, then picks one of three modes based on workload fit + per-rank CPU RAM:</p>
<ul>
<li><strong>Mode A — GPU-resident / DDP-friendly</strong> (<code>force_all_persistent=True</code>). Chosen when the searcher places <code>n_persist == N_chunk</code> under the capacity budget — the model fits entirely on GPU and no CPU offload is needed. This is the throughput winner on a 3090 rig: DDP’s bucketed NCCL allreduce beats ProTrain’s per-param grad sync, and the M7 benchmark measured <strong>3.64x</strong> scaling at world_size=4 on PCIe Gen3.</li>
<li><strong>Mode B — replicated CPU-offload</strong> (<code>zero3_shard=False</code>). Chosen when the model needs offload AND per-rank CPU RAM can hold the full non-persistent chunk set (<code>cpu_ram_per_rank &gt;= (N_chunk - n_persist) * S_chunk</code>). Each rank holds a full replicated copy of every non-persistent chunk; no per-chunk collectives, so it’s ~1.9x faster than sharded on PCIe Gen3.</li>
<li><strong>Mode C — ZeRO-3 sharded CPU-offload</strong> (<code>zero3_shard=True</code>). Chosen when per-rank CPU RAM is too tight for replication but fits a <code>1/world_size</code> shard per chunk. Measured throughput is <strong>0.70x</strong> single-rank on 4x 3090 — the <code>all_gather</code> / <code>reduce_scatter</code> collectives dominate on PCIe Gen3 Llama-3B. Picked only when Mode B can’t fit.</li>
<li><strong>Otherwise</strong> — <code>RuntimeError</code>. The model doesn’t fit on this node even with sharding; user must scale up (more nodes / larger RAM / smaller model) before retrying.</li>
</ul>
<p><strong>CPU-RAM-per-rank estimate.</strong> <code>node RAM available / world_size</code>. Probes <code>psutil.virtual_memory().available</code> first (preferred; part of Axolotl’s env already), falls back to <code>/proc/meminfo:MemAvailable</code> on Linux. Returns 0 when neither probe succeeds — the selector then prefers Mode A and raises if offload is required. Caveats: the divide-by-world-size model is pessimistic on NUMA-bound allocations and optimistic on heterogeneous multi-host setups where the smallest node’s RAM binds. Users whose production topology doesn’t match “node RAM / world_size” should set <code>protrain_auto_mode: false</code> and pick the mode explicitly via <code>protrain_force_all_persistent</code> / <code>protrain_zero3_shard</code>.</p>
<p><strong>Mode B over Mode C — throughput trade-off.</strong> The selector prefers Mode B over Mode C even when C would save pinned RAM, because B is ~1.9x faster on PCIe Gen3 and “CPU RAM fits replicated” is the loose binding constraint. Users with binding CPU pressure (e.g., a 96 GB system driving 8 ranks of a model whose non-persistent set is 80 GB replicated but 10 GB sharded) should set <code>protrain_auto_mode: false, protrain_zero3_shard: true</code> to force Mode C.</p>
<p><strong>Explicit overrides.</strong> <code>protrain_auto_mode: false</code> bypasses the selector and honours <code>protrain_force_all_persistent</code> / <code>protrain_zero3_shard</code> verbatim (following the pre-auto-mode table above). When <code>protrain_auto_mode: true</code> and the user still sets one of the mode flags, the selector logs a warning and proceeds with the auto-selected mode — the flags are explicitly documented as overrides that require turning auto-mode off to take effect.</p>
<p><strong>Shard layout.</strong> Rank <code>r</code> owns the byte range <code>[r * shard_bytes, (r + 1) * shard_bytes)</code> within each region. <code>shard_bytes = region_bytes_padded / world_size</code>, where <code>region_bytes_padded</code> is rounded up to <code>lcm(region_element_size, world_size)</code> — this guarantees both (a) the shard boundary is dtype-aligned (so <code>.view(fp16)</code> on the pool buffer after <code>all_gather</code> doesn’t raise “offset not aligned”) and (b) every rank holds an equal shard size (required by <code>all_gather_into_tensor</code> / <code>reduce_scatter_tensor</code>). Params straddling shard boundaries are NOT special-cased — each rank just holds the bytes it owns; reassembly is byte-exact under <code>all_gather</code>’s contiguous layout. Regions within a chunk are gap-tolerant: per-region padding lives inside a transient scratch buffer at gather/reduce time rather than the pool buffer’s byte layout, so params always index into the pool buffer at their original <code>aligned_offsets</code>.</p>
<p><strong>Memory-safety contract.</strong> GPU peak is unchanged by sharding (the gather reconstructs the full chunk on GPU via <code>all_gather_into_tensor</code> regardless), so <code>cost/memory.py::estimate_peak</code> ignores <code>HardwareProfile.zero3_shard</code>. The per-rank pinned CPU footprint DOES scale with sharding — <code>cost/memory.py::estimate_cpu_footprint</code> returns <code>(N_chunk - n_persist) * S_chunk / world_size</code> under sharding vs.&nbsp;the full product under replication. The searcher’s GPU-capacity gate (the only feasibility filter today) is therefore sharding-agnostic; the explicit <code>zero3_shard</code> plumbing on <code>HardwareProfile</code> exists so future CPU-budget filters (if added) can consult it.</p>
<section id="nccl-measurement-gap" class="level4">
<h4 class="anchored" data-anchor-id="nccl-measurement-gap">NCCL measurement gap</h4>
<p><code>protrain_model_wrapper</code> runs from <code>plugin.post_model_load</code>, which fires during model loading at <code>loaders/model.py:191</code> — BEFORE the Trainer / Accelerate path initializes the distributed process group. So when the profiler calls <code>measure_nccl(world_size&gt;1)</code>, <code>dist.is_initialized()</code> is False, the call falls through to empty <code>nccl_gather_s</code> / <code>nccl_reduce_s</code> tables, and the trace records <code>world=1</code> regardless of actual world size.</p>
<p>This gap is functionally inert in the auto-selected Mode A and Mode B paths. Mode A (DDP) keeps every chunk persistent — DDP itself owns the cross-rank allreduce, and ProTrain issues no per-chunk collectives, so the cost model never reads the NCCL tables. Mode B (replicated CPU offload) likewise issues no per-chunk collectives. Only Mode C (ZeRO-3 sharded) actually consumes <code>nccl_gather_s</code> / <code>nccl_reduce_s</code> — and the auto-selector picks Mode C last (only when per-rank CPU RAM can’t hold the replicated non-persistent set).</p>
<p>Workaround for Mode C operators: run <code>scripts/protrain/measure_nccl.py</code> once on the target rig under a real distributed launcher (it inits the process group itself and writes a JSON of <code>{payload_bytes: seconds}</code> for both gather and reduce-scatter). The output can be hand-loaded into the trace before search runs, or — more practically — used to validate that Mode C predictions match the standalone benchmark on the operator’s interconnect.</p>
<p>Late-bind path: <code>plugin.post_trainer_create</code> calls <code>_remeasure_nccl_and_research(wrapped)</code> after Accelerate brings up dist. When <code>world_size &gt; 1</code> and the cached trace’s NCCL tables are empty, the helper measures NCCL on the live process group, splices the populated tables + actual world into the trace via <code>dataclasses.replace</code>, persists the updated trace under a new cache key (so the next multi-rank run hits it directly without re-measuring), and re-runs <code>search()</code> with the same layout + capacity + hardware profile. The chunk manager is NOT rebuilt — optimizer state slots are already wired into the trainer — so the running step uses the bootstrap config; if the post-NCCL search picks a different <code>cfg</code>/<code>block_map</code>, a WARN is logged and <code>WrappedModel.search_result</code> is overwritten so future cost-model-based decisions reflect real comm cost. Subsequent multi-rank runs hit the cache and pick the new config from the start. Mode A / Mode B remain unaffected since they don’t consume the NCCL tables.</p>
</section>
<section id="multi-gpu-measured-throughput-4x-3090" class="level4">
<h4 class="anchored" data-anchor-id="multi-gpu-measured-throughput-4x-3090">Multi-GPU — Measured Throughput (4x 3090)</h4>
<p>Benchmark: fresh-init Llama-3B + LoRA r=8, bs=2 per rank, seq=256, fp16. 6 iterations per mode, 2 warm-up discarded, median of the remaining 4 is reported. GPUs 1, 4, 5, 7 on a PCIe-Gen3 test rig (no NVLink). Reproduce with <code>CUDA_VISIBLE_DEVICES=1,4,5,7 CUDA_DEVICE_ORDER=PCI_BUS_ID python scripts/benchmark_multi_gpu.py</code>; full JSON at <code>scripts/multi_gpu_benchmark_results.json</code>.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>Mode</th>
<th>World</th>
<th>Throughput (samples/s)</th>
<th>Scaling vs 1-GPU</th>
<th>Per-rank GPU peak</th>
<th>Per-rank CPU pinned</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Single-rank (baseline)</td>
<td>1</td>
<td>8.48</td>
<td>1.00x</td>
<td>5.36 GB</td>
<td>0.00 GB</td>
</tr>
<tr class="even">
<td>DDP (<code>force_all_persistent=True</code>)</td>
<td>4</td>
<td>30.90</td>
<td>3.64x</td>
<td>5.38 GB</td>
<td>0.00 GB</td>
</tr>
<tr class="odd">
<td>Replicated offload (<code>zero3_shard=False</code>)</td>
<td>4</td>
<td>11.06</td>
<td>1.30x</td>
<td>3.09 GB</td>
<td>3.82 GB</td>
</tr>
<tr class="even">
<td>ZeRO-3 sharded (<code>zero3_shard=True</code>)</td>
<td>4</td>
<td>5.93</td>
<td>0.70x</td>
<td>3.09 GB</td>
<td>0.96 GB</td>
</tr>
</tbody>
</table>
<p><strong>How to pick a mode on a 3090 rig.</strong> DDP is the clear throughput winner when the model + optimizer fit on one card (the 7B-LoRA / 3B-full regime) — outer-bucketed NCCL allreduce amortizes better than ProTrain’s per-param grad sync and keeps every chunk GPU-resident. Reach for <strong>replicated offload</strong> only when one card can’t hold the full model at peak; per-rank GPU drops ~42% (5.4 GB → 3.1 GB here) at a ~3x throughput cost vs DDP. <strong>ZeRO-3 sharded</strong> is only worth it when CPU RAM is the binding constraint — it cuts per-rank pinned CPU by almost exactly <code>1/world_size</code> (3.82 GB → 0.96 GB here, a 4.0x reduction, matching world_size) but pays an additional ~1.9x iteration-time penalty from the per-chunk <code>all_gather</code> + <code>reduce_scatter</code> collectives on PCIe Gen3. For 7B LoRA on 4x 3090 with NVMe or 128+ GB system RAM, stay on DDP with <code>force_all_persistent=True</code>.</p>
<p>Note: ZeRO-3 throughput fell below the “within 15% of replicated” design target in this measurement — at Llama-3B / bs=2 / seq=256 the compute per chunk is too small to hide the two per-chunk collectives on PCIe. The ratio should improve at larger batch size / sequence length where compute dominates; see M7 profiler runs before broad deployment.</p>
</section>
</section>
</section>
<section id="out-of-scope" class="level2">
<h2 class="anchored" data-anchor-id="out-of-scope">Out of Scope</h2>
<p>Mirrors <code>plan.md</code>:
- A100/H100, NVLink, InfiniBand, multi-node
- TP, PP, any non-ZeRO-3 parallelism
- FP8/FP4, quantization, FlashAttention variants
- Windows / macOS
- Edits to Axolotl core files outside this plugin package — ProTrain is additive, DeepSpeed/FSDP/Unsloth paths unchanged</p>
</section>
<section id="design-decisions-previously-open-questions-now-resolved" class="level2">
<h2 class="anchored" data-anchor-id="design-decisions-previously-open-questions-now-resolved">Design Decisions (previously open questions, now resolved)</h2>
<ol type="1">
<li><strong>α fragmentation factor = 1.10</strong> — matches paper’s “up to 10% overestimate” (§3.3). M1 records ground truth; M4 can recalibrate if observed 3090 fragmentation diverges.</li>
<li><strong>Pinned-memory allocator:</strong> <code>ctypes</code> → <code>cudaHostAlloc</code> directly. ~50 LOC, zero new deps, matches App B.2 precisely (avoids <code>CUDAHostAllocator</code> pow-2 rounding). DeepSpeed’s <code>PinnedMemoryAllocator</code> rejected: may inherit same wart, adds import-graph weight.</li>
<li><strong>CPU FusedAdam source:</strong> <code>deepspeed.ops.adam.DeepSpeedCPUAdam</code>. Paper builds directly on ZeRO-Offload’s CPU Adam. Pure-Python reimpl is &gt;10× slower and would collapse the T_bwd / T_cpu_optim overlap window the cost model assumes. DeepSpeed is already in Axolotl’s env.</li>
<li><strong>S_chunk grid:</strong> <code>{32, 64, 128, 256} MB</code>. 7B Llama blocks are ~200 MB fp16 → chunks want to be block-scale. 16 MB is too fine-grained; per-chunk sync overhead dominates. M2 agent extends the grid if optimum lands at an endpoint.</li>
<li><strong>SWAP path:</strong> paper-real D2H/H2D wrapper on <code>_swap_stream</code>, backed by <code>ActivationSwapPool</code> (pinned host slots sized <code>n_swap × prefetch_depth × max_act_bytes</code>). Searcher’s CPU-feasibility gate refuses <code>n_swap &gt; 0</code> candidates whose pool would not fit <code>cpu_capacity_bytes</code>. On RTX 3090 / 3090 Ti (12 GB/s PCIe ceiling, no NVLink) the searcher rarely selects <code>n_swap &gt; 0</code> — paper §3.1.2 — so the path is tested-but-unused infrastructure on this hardware class. Validated end-to-end via the wrapper-injection path with <code>n_swap_override</code>.</li>
</ol>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/docs\.axolotl\.ai");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>